/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutInterests: typeof import('./src/components/AboutInterests.vue')['default']
    GlobalMenu: typeof import('./src/components/GlobalMenu.vue')['default']
    PageMenu: typeof import('./src/components/PageMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPreview: typeof import('./src/components/Work/ScrollPreview.vue')['default']
    ShaderBackground: typeof import('./src/components/ShaderBackground.vue')['default']
    WorkModale: typeof import('./src/components/Work/WorkModale.vue')['default']
  }
}
